# Generated by Django 4.2.21 on 2025-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('last_questionnaire', models.CharField(max_length=50)),
                ('rating', models.CharField(default='neutral', max_length=5)),
            ],
        ),
    ]
