# Generated by Django 4.2.21 on 2025-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_patient_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rating',
            field=models.CharField(default='neutral', max_length=7),
        ),
    ]
